
POST http://localhost:5000/purchase/add
Content-Type: application/json
Authorization: B2F8DA2204511F448318F5D3C56B52B05F1DA1B5-1544776249434-xtest

{
  "place" : "asda",
  "thing": "spajjjjce",
  "money" : 50
}
###

POST http://localhost:5000/purchase/add
Content-Type: application/json
Authorization: 163796DE27A1EE3ED5498AFAFB35A96B20299F84-1544776757308-xtest1

{
"place" : "fff",
"thing": "fff",
"money" : 5505
}
###

GET http://localhost:5000/purchase/9
Authorization: 4E6EABE408F17DC3FB50070D026AE61B3DE1DCBE-1544778872786-xtest

###